import os
from datetime import datetime, timedelta
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from sqlalchemy import func
from database import SessionLocal
from models import ProcessedComment

def generate_weekly_report():
    """Generates a PDF report summarizing the last 7 days of sentiment data."""
    db = SessionLocal()
    try:
        now = datetime.utcnow()
        seven_days_ago = now - timedelta(days=7)

        # 1. Fetch data
        total_comments = db.query(func.count(ProcessedComment.id)).filter(ProcessedComment.created_at >= seven_days_ago).scalar() or 0
        
        sentiments = db.query(ProcessedComment.sentiment, func.count(ProcessedComment.id))\
            .filter(ProcessedComment.created_at >= seven_days_ago)\
            .group_by(ProcessedComment.sentiment).all()
        sentiment_dict = {s: c for s, c in sentiments}
        
        # 2. Build PDF
        os.makedirs("reports", exist_ok=True)
        filename = f"reports/SwaraSense_Weekly_{now.strftime('%Y%m%d')}.pdf"
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, spaceAfter=20, textColor=colors.HexColor("#4F46E5"))
        h2_style = ParagraphStyle('H2Style', parent=styles['Heading2'], fontSize=14, spaceAfter=10, textColor=colors.HexColor("#1F2937"))
        normal_style = styles['Normal']

        elements = []
        
        # Title
        elements.append(Paragraph(f"SwaraSense Weekly Executive Report", title_style))
        elements.append(Paragraph(f"Generated on: {now.strftime('%B %d, %Y')}", normal_style))
        elements.append(Spacer(1, 20))
        
        # Summary
        elements.append(Paragraph("Weekly Summary", h2_style))
        elements.append(Paragraph(f"Total Comments Processed: <b>{total_comments}</b>", normal_style))
        elements.append(Spacer(1, 10))
        
        # Sentiment Breakdown
        elements.append(Paragraph("Sentiment Breakdown", h2_style))
        data = [['Sentiment', 'Count']]
        for sent in ['positive', 'negative', 'neutral', 'sarcastic']:
            count = sentiment_dict.get(sent, 0)
            data.append([sent.capitalize(), str(count)])
            
        table = Table(data, colWidths=[200, 100])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F9FAFB")),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 20))
        
        # Footer Note
        elements.append(Paragraph("This is an automated report generated by SwaraSense.", normal_style))
        
        doc.build(elements)
        print(f"Weekly PDF generated at {filename}")
        return filename
    except Exception as e:
        print(f"Error generating report: {e}")
        return None
    finally:
        db.close()
